### ISSUE TITLE
Specify where screenshot image is saved

### ISSUE THREAD

**Issue by arielelkin** [st3fan/iphone-experiments#1]
Where does `[ScreenShotViewController  renderScrollViewToImage]` actually save the screenshot? The app's `/tmp` folder is empty. 

This is on Xcode 5.0.2

**Comment by st3fan** [comment]
When you run this in the simulator, the screenshots are stored in the `/tmp` directory of OS X.

**Comment by arielelkin** [comment]
Awesome. Please put it in the Readme file?
